chore: Use `'worklet'` directive directly in processor functions (#9154)
## Summary

### Fixed issue

Using tamagui with reanimated, I get this error. I see the other files
in the processors folder have the worklets directive already.

```
Error: [Worklets] Tried to synchronously call a non-worklet function processGap on the UI thread.
See https://docs.swmansion.com/react-native-worklets/docs/guides/troubleshooting#tried-to-synchronously-call-a-non-worklet-function-on-the-ui-thread for more details.
```

### Cleanup

Other processors were similarly updated to use in-function worklet
directives.

---------

Co-authored-by: Mateusz Łopaciński <lop.mateusz.2001@gmail.com>
Co-authored-by: Tomasz Żelawski <tzelawski@gmail.com>